### ISSUE TITLE
onm-cli fails to load sysrepo modules

### ISSUE THREAD

**Issue by adaraiseh** [okda-networks/onm-cli#43]
```
amjad@bullseye:~/Documents/onm-development/onm-cli$ sysrepoctl -l
Sysrepo repository: /home/amjad/onm-sysrepo

Module Name                | Revision   | Flags | Owner       | Startup Perms | Submodules | Features                                                                                                                                               
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
frr-affinity-map           | 2022-11-03 | I     | amjad:frr   | 660           |            |                                                                                                                                                        
frr-bfdd                   | 2019-05-09 | I     | amjad:frr   | 660           |            |                                                                                                                                                        
frr-filter                 | 2019-07-04 | I     | amjad:frr   | 660           |            |                                                                                                                                                        
frr-if-rmap                | 2023-04-09 | I     | amjad:frr   | 660           |            |                                                                                                                                                        
frr-interface              | 2020-02-05 | I     | amjad:frr   | 660           |            |                                                                                                                                                        
frr-isisd                  | 2021-02-15 | I     | amjad:frr   | 660           |            |                                                                                                                                                        
frr-nexthop                | 2019-08-15 | I     | amjad:frr   | 660           |            |                                                                                                                                                        
frr-ripd                   | 2019-09-09 | I     | amjad:frr   | 660           |            |                                                                                                                                                        
frr-ripngd                 | 2019-09-09 | I     | amjad:frr   | 660           |            |                                                                                                                                                        
frr-route-map              | 2019-07-01 | I     | amjad:frr   | 660           |            |                                                                                                                                                        
frr-route-types            | 2018-03-28 | I     | amjad:frr   | 660           |            |                                                                                                                                                        
frr-vrf                    | 2019-12-06 | I     | amjad:frr   | 660           |            |                                                                                                                                                        
iana-if-type               | 2017-01-19 | I     | amjad:amjad | 600           |            |                                                                                                                                                        
ieee802-dot1q-types        | 2018-03-07 | I     | amjad:amjad | 600           |            |                                                                                                                                                        
ietf-access-control-list   | 2019-03-04 | I     | amjad:amjad | 600           |            | match-on-eth match-on-ipv4 match-on-ipv6 match-on-tcp match-on-udp eth ipv4 ipv6 mixed-eth-ipv4 mixed-eth-ipv6 mixed-eth-ipv4-ipv6 interface-attachment
ietf-datastores            | 2018-02-14 | I     | amjad:amjad | 444           |            |                                                                                                                                                        
ietf-ethertypes            | 2019-03-04 | I     | amjad:amjad | 600           |            |                                                                                                                                                        
ietf-factory-default       | 2020-08-31 | I     | amjad:amjad | 600           |            | factory-default-datastore                                                                                                                              
ietf-if-extensions         | 2020-07-29 | I     | amjad:amjad | 600           |            | sub-interfaces                                                                                                                                         
ietf-if-vlan-encapsulation | 2020-07-13 | I     | amjad:amjad | 600           |            |                                                                                                                                                        
ietf-inet-types            | 2013-07-15 | i     |             |               |            |                                                                                                                                                        
ietf-interfaces            | 2018-02-20 | I     | amjad:amjad | 600           |            | if-mib                                                                                                                                                 
ietf-ip                    | 2018-02-22 | I     | amjad:amjad | 600           |            |                                                                                                                                                        
ietf-netconf               | 2013-09-29 | I     | amjad:amjad | 644           |            |                                                                                                                                                        
ietf-netconf-acm           | 2018-02-14 | I     | amjad:amjad | 600           |            |                                                                                                                                                        
ietf-netconf-notifications | 2012-02-06 | I     | amjad:amjad | 644           |            |                                                                                                                                                        
ietf-netconf-with-defaults | 2011-06-01 | I     | amjad:amjad | 444           |            |                                                                                                                                                        
ietf-origin                | 2018-02-14 | I     | amjad:amjad | 444           |            |                                                                                                                                                        
ietf-packet-fields         | 2019-03-04 | I     | amjad:amjad | 600           |            |                                                                                                                                                        
ietf-routing-types         | 2017-12-04 | I     | amjad:frr   | 660           |            |                                                                                                                                                        
ietf-vrrp                  | 2018-01-09 | I     | amjad:amjad | 600           |            |                                                                                                                                                        
ietf-yang-library          | 2019-01-04 | I     | amjad:amjad | 644           |            |                                                                                                                                                        
ietf-yang-metadata         | 2016-08-05 | i     |             |               |            |                                                                                                                                                        
ietf-yang-schema-mount     | 2019-01-14 | I     | amjad:amjad | 664           |            |                                                                                                                                                        
ietf-yang-structure-ext    | 2020-06-17 | i     |             |               |            |                                                                                                                                                        
ietf-yang-types            | 2013-07-15 | i     |             |               |            |                                                                                                                                                        
sysrepo-factory-default    | 2023-02-23 | I     | amjad:amjad | 600           |            |                                                                                                                                                        
sysrepo-monitoring         | 2023-08-11 | I     | amjad:amjad | 600           |            |                                                                                                                                                        
sysrepo-plugind            | 2022-08-26 | I     | amjad:amjad | 644           |            |    
yang                       | 2022-06-16 | I     | amjad:amjad | 444           |            |                                                                                                                                                        

Flags meaning: I - Installed/i - Imported; R - Replay support

amjad@bullseye:~/Documents/onm-development/onm-cli$ sysrepoctl -V
sysrepoctl - sysrepo YANG schema manipulation tool, compiled with libsysrepo v2.2.105 (SO v7.19.3)
amjad@bullseye:~/Documents/onm-development/onm-cli$ 
amjad@bullseye:~/Documents/onm-development/onm-cli$ ./onmcli 
[INF] Connection 1476 created.
[INF] Session 3194 (user "amjad", CID 1476) created.

onmcli version: 0.1.0
by Okda networks (c) 2023
bullseye> en
bullseye# sysrepo load-modules 
  yang commands generated successfully for module=ietf-yang-schema-mount
  yang commands generated successfully for module=sysrepo
  yang commands generated successfully for module=ietf-netconf-acm
  yang commands generated successfully for module=ietf-yang-library
  yang commands generated successfully for module=sysrepo-monitoring
  yang commands generated successfully for module=sysrepo-plugind
  yang commands generated successfully for module=ietf-interfaces
  yang commands generated successfully for module=frr-vrf
  yang commands generated successfully for module=frr-interface
  yang commands generated successfully for module=frr-filter
  yang commands generated successfully for module=frr-route-map
Segmentation fault

```
GDB debugs:
```
(No debugging symbols found in ./onmcli)
(gdb) run
Starting program: /home/amjad/Documents/onm-development/onm-cli/onmcli 
BFD: /lib64/ld-linux-x86-64.so.2: unknown type [0x13] section `.relr.dyn'
warning: `/lib64/ld-linux-x86-64.so.2': Shared library architecture unknown is not compatible with target architecture i386:x86-64.
warning: `/lib64/ld-linux-x86-64.so.2': Shared library architecture unknown is not compatible with target architecture i386:x86-64.
BFD: /lib/x86_64-linux-gnu/libc.so.6: unknown type [0x13] section `.relr.dyn'
warning: `/lib/x86_64-linux-gnu/libc.so.6': Shared library architecture unknown is not compatible with target architecture i386:x86-64.
BFD: /lib/x86_64-linux-gnu/libdl.so.2: unknown type [0x13] section `.relr.dyn'
warning: `/lib/x86_64-linux-gnu/libdl.so.2': Shared library architecture unknown is not compatible with target architecture i386:x86-64.
BFD: /lib/x86_64-linux-gnu/libpthread.so.0: unknown type [0x13] section `.relr.dyn'
warning: `/lib/x86_64-linux-gnu/libpthread.so.0': Shared library architecture unknown is not compatible with target architecture i386:x86-64.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[INF] Connection 1477 created.
[INF] Session 3195 (user "amjad", CID 1477) created.


onmcli version: 0.1.0
by Okda networks (c) 2023
bullseye> 
bullseye> 
bullseye> en
bullseye# 
bullseye# 
bullseye# sysrepo load-modules 
  yang commands generated successfully for module=ietf-yang-schema-mount
  yang commands generated successfully for module=sysrepo
  yang commands generated successfully for module=ietf-netconf-acm
  yang commands generated successfully for module=ietf-yang-library
  yang commands generated successfully for module=sysrepo-monitoring
  yang commands generated successfully for module=sysrepo-plugind
  yang commands generated successfully for module=ietf-interfaces
  yang commands generated successfully for module=frr-vrf
  yang commands generated successfully for module=frr-interface
  yang commands generated successfully for module=frr-filter
  yang commands generated successfully for module=frr-route-map

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7d25159 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
(gdb) 
```

**Comment by Ali-aqrabawi** [comment]
@adaraiseh  can you do `make clean` then `make debug` and run GDB again. after it fail run `bt` inside gdb `(gdb) bt` and include the outputs

**Comment by adaraiseh** [comment]
```
onmcli version: 0.1.0

by Okda networks (c) 2023

bullseye> 

bullseye> en

bullseye# sysrepo load-modules 

  yang commands generated successfully for module=ietf-yang-schema-mount

  yang commands generated successfully for module=sysrepo

  yang commands generated successfully for module=ietf-netconf-acm

  yang commands generated successfully for module=ietf-yang-library

  yang commands generated successfully for module=sysrepo-monitoring

  yang commands generated successfully for module=sysrepo-plugind

  yang commands generated successfully for module=ietf-interfaces

  yang commands generated successfully for module=frr-vrf

  yang commands generated successfully for module=frr-interface

  yang commands generated successfully for module=frr-filter

  yang commands generated successfully for module=frr-route-map



Program received signal SIGSEGV, Segmentation fault.

0x00007ffff7d25159 in ?? () from /lib/x86_64-linux-gnu/libc.so.6

(gdb) bt
#0  0x00007ffff7d25159 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ffff7c6dc9e in strdup () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x0000555555558a90 in register_cmd_list (cli=0x55555556c2a0, y_node=0x5555556b00c0) at src/commands/yang_core/cmd_list.c:136
#3  0x0000555555559df0 in register_node_routine (cli=0x55555556c2a0, schema=0x5555556b00c0) at src/commands/yang_core/y_cmd_generator.c:33
#4  0x0000555555559eab in register_commands_schema (schema=0x5555556abca0, cli=0x55555556c2a0) at src/commands/yang_core/y_cmd_generator.c:60
#5  0x0000555555556dcc in mod2cmd_generate (cli=0x55555556c2a0, module=0x55555564ad60) at src/commands/sysrepo_cmd.c:23
#6  0x000055555555700c in cmd_sysrepo_load_module (cli=0x55555556c2a0, c=0x55555556efc0, cmd=0x55555556f0a0 "sysrepo load-modules", argv=0x555555597af8, argc=0) at src/commands/sysrepo_cmd.c:81
#7  0x0000555555563180 in cli_int_execute_pipeline (cli=0x55555556c2a0, pipeline=0x555555597ae0) at lib/libcli/libcli.c:3276
#8  0x000055555555ccd0 in cli_run_command (cli=0x55555556c2a0, command=0x55555558de90 "sysrepo load-modules ") at lib/libcli/libcli.c:1046
#9  0x000055555555f46a in cli_loop (cli=0x55555556c2a0, sockfd=9) at lib/libcli/libcli.c:1946
#10 0x0000555555564d5e in handle_session (fd=9) at src/onm_cli.c:22
#11 0x0000555555564ce5 in main () at src/onm_main.c:75
(gdb) 
```onmcli version: 0.1.0

by Okda networks (c) 2023

bullseye> 

bullseye> en

bullseye# sysrepo load-modules 

  yang commands generated successfully for module=ietf-yang-schema-mount

  yang commands generated successfully for module=sysrepo

  yang commands generated successfully for module=ietf-netconf-acm

  yang commands generated successfully for module=ietf-yang-library

  yang commands generated successfully for module=sysrepo-monitoring

  yang commands generated successfully for module=sysrepo-plugind

  yang commands generated successfully for module=ietf-interfaces

  yang commands generated successfully for module=frr-vrf

  yang commands generated successfully for module=frr-interface

  yang commands generated successfully for module=frr-filter

  yang commands generated successfully for module=frr-route-map



Program received signal SIGSEGV, Segmentation fault.

0x00007ffff7d25159 in ?? () from /lib/x86_64-linux-gnu/libc.so.6

(gdb) bt
#0  0x00007ffff7d25159 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ffff7c6dc9e in strdup () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x0000555555558a90 in register_cmd_list (cli=0x55555556c2a0, y_node=0x5555556b00c0) at src/commands/yang_core/cmd_list.c:136
#3  0x0000555555559df0 in register_node_routine (cli=0x55555556c2a0, schema=0x5555556b00c0) at src/commands/yang_core/y_cmd_generator.c:33
#4  0x0000555555559eab in register_commands_schema (schema=0x5555556abca0, cli=0x55555556c2a0) at src/commands/yang_core/y_cmd_generator.c:60
#5  0x0000555555556dcc in mod2cmd_generate (cli=0x55555556c2a0, module=0x55555564ad60) at src/commands/sysrepo_cmd.c:23
#6  0x000055555555700c in cmd_sysrepo_load_module (cli=0x55555556c2a0, c=0x55555556efc0, cmd=0x55555556f0a0 "sysrepo load-modules", argv=0x555555597af8, argc=0) at src/commands/sysrepo_cmd.c:81
#7  0x0000555555563180 in cli_int_execute_pipeline (cli=0x55555556c2a0, pipeline=0x555555597ae0) at lib/libcli/libcli.c:3276
#8  0x000055555555ccd0 in cli_run_command (cli=0x55555556c2a0, command=0x55555558de90 "sysrepo load-modules ") at lib/libcli/libcli.c:1046
#9  0x000055555555f46a in cli_loop (cli=0x55555556c2a0, sockfd=9) at lib/libcli/libcli.c:1946
#10 0x0000555555564d5e in handle_session (fd=9) at src/onm_cli.c:22
#11 0x0000555555564ce5 in main () at src/onm_main.c:75
(gdb)
