### ISSUE TITLE
cli crash on variables Tab

### ISSUE THREAD

**Issue by adaraiseh** [okda-networks/onm-cli#48]
The cli crashed when I did a question mark while editing ace name:
```
bullseye# sysrepo load-modules 
  yang commands generated successfully for module=ietf-yang-schema-mount
  yang commands generated successfully for module=sysrepo
  yang commands generated successfully for module=ietf-netconf-acm
  yang commands generated successfully for module=ietf-yang-library
  yang commands generated successfully for module=sysrepo-monitoring
  yang commands generated successfully for module=sysrepo-plugind
  yang commands generated successfully for module=ietf-interfaces
  yang commands generated successfully for module=frr-vrf
  yang commands generated successfully for module=frr-interface
  yang commands generated successfully for module=frr-filter
  yang commands generated successfully for module=frr-route-map
  yang commands generated successfully for module=frr-isisd
  yang commands generated successfully for module=frr-bfdd
  yang commands generated successfully for module=frr-nexthop
  yang commands generated successfully for module=frr-ripd
  yang commands generated successfully for module=frr-ripngd
  yang commands generated successfully for module=frr-affinity-map
  yang commands generated successfully for module=ietf-access-control-list
  yang commands generated successfully for module=ietf-vrrp
bullseye# conf terminal 
bullseye(config)# conf terminal 
Invalid command "conf"
bullseye(config)# acls 
  [delete]             delete container
  <cr>
bullseye(config)# acls 
bullseye(config-acls)# acl 
  <name>               The name of the access list.  A device MAY further
                       restrict the length of this name; space and special
                       characters are not allowed.
bullseye(config-acls)# acl test 
  [delete]             to delete the list entry
  <cr>
bullseye(config-acls)# acl test 
bullseye(config-acl[test])# aces 
  [delete]             delete container
  <cr>
bullseye(config-acl[test])# aces 
bullseye(config-aces)# ace 
  <name>               A unique name identifying this ACE.
bullseye(config-aces)# ace test
bullseye(config-ace[test])# 
  help                 Show available commands
  quit                 Disconnect
  logout               Disconnect
  history              Show a list of previously run commands
  exit                 exit to prev mode
  commit               commit changes to sysrepo cdb
  print                print the candidate/running config
  discard-changes      discard all current changes
  name                 configure name (ietf-access-control-list) [leaf]
  matches              configure matches (ietf-access-control-list) [contain]
  actions              configure actions (ietf-access-control-list) [contain]
bullseye(config-ace[test])# matches 
  [delete]             delete container
  <cr>
bullseye(config-ace[test])# name    
  <value>              A unique name identifying this ACE.
    [delete]           delete name
bullseye(config-ace[test])# name tes
Program received signal SIGSEGV, Segmentation fault.
0x000055555555ad0d in optagr_get_compl ()
(gdb) bt 
#0  0x000055555555ad0d in optagr_get_compl ()
#1  0x00005555555640ef in cli_get_optarg_comphelp ()
#2  0x0000555555564760 in cli_int_parse_optargs ()
#3  0x000055555555d88a in cli_get_completions ()
#4  0x000055555555eaa4 in cli_loop ()
#5  0x0000555555565426 in handle_session ()
#6  0x00005555555653ad in main ()
```

**Comment by adaraiseh** [comment]
correction, the problem happens when you tab a key value :
```
bullseye# conf t
bullseye(config)# acls 
bullseye(config-acls)# acl pressTabHereToReproduce 
Program received signal SIGSEGV, Segmentation fault.
0x000055555555ad0d in optagr_get_compl ()
(gdb) bt 
#0  0x000055555555ad0d in optagr_get_compl ()
#1  0x00005555555640ef in cli_get_optarg_comphelp ()
#2  0x0000555555564760 in cli_int_parse_optargs ()
#3  0x000055555555d88a in cli_get_completions ()
#4  0x000055555555eaa4 in cli_loop ()
#5  0x0000555555565426 in handle_session ()
#6  0x00005555555653ad in main ()

```
